sonar.projectKey=gajdakrz_sport-scores
sonar.organization=gajdakrz
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=\
  **/public/bundles/**, \
  **/vendor/**, \
  **/var/**, \
  **/migrations/**, \
  **/node_modules/**
